### DISCUSSION TITLE
Setup - UHC Computer

### DISCUSSION THREAD

**Discussion by ran-codes** [Drexel-UHC/duckdb-dbt-template#3] [Notes]
Documenting setting up DBT and requiring software on a UHC desktop.

### Signup
- [ ] [GitHub Account](https://github.com/join)
- [ ] [ChatGPT Account](https://auth0.openai.com/u/signup/identifier?state=hKFo2SB6Q3pYdUJud1pVV0tQZ3Y3Y2hsZ1ZmZ0lxaUtXVTJEYqFur3VuaXZlcnNhbC1sb2dpbqN0aWTZIENpLVdzcGdKZ1dkWUdEMUprdXB6eDhrRFNGSDBac21Wo2NpZNkgVGRKSWNiZTE2V29USHROOTVueXl3aDVFNHlPbzZJdEc)

### Prep:  Install the required software 
- [x] [GitHub Desktop](https://desktop.github.com/)
- [x] Python 3.10 via the Microsoft Store
- [x] [VS-code](https://code.visualstudio.com/docs/?dv=win)
   - [x] extension: Python
   - [x] extension: DBT Power User
- [x] Open Windows Powershell as admin then allow local scripts to be run via ` Set-ExecutionPolicy RemoteSigned` then confirm `Y`

### Clone + Set up DBT
- [x] clone `hcup-dbt`
- [x] Create a Python local environment with venv
   - [x] `cntrl shift p` to open command palette then type Python: Create Environment
   - [x] Select Python 3.10
   - [x] activate venv with `.\.venv\Scripts\activate` in the terminal
- [x] install requiremed dependencies `pip install -r requirements.txt`
- [x] `dbt compile` to check everything works! 😄 then happy modeling!!!

### `profiles.yml`

```yml
hcup:
  outputs:
    dev:
      type: duckdb
      path: hcup-dev.duckdb
      schema: parquet
      extensions:
        - httpfs
        - parquet
      external_root: 'C:\Users\rl627\Desktop\Git\hcup-dbt\external\'      
    stage:
      type: duckdb
      path: hcup-dev.duckdb
      schema: csv
      extensions:
        - httpfs
        - parquet
      external_root: '\\files.drexel.edu\encrypted\SOPH\UHC\SchnakeMahl_HCUP\dbt\v0\stage\'
    prod:
      type: duckdb
      path: hcup-prod.duckdb
      schema: parquet
      extensions:
        - httpfs
        - parquet
      external_root: '\\files.drexel.edu\encrypted\SOPH\UHC\SchnakeMahl_HCUP\dbt\v0\models\'
  target:  dev
```
